export const mobileData = [
  {
    id: 1,
    title: "Google Pixel 10",
    image: "/Images/Mobiles/google pixel 10.webp",
    price: 79999,
    processor: "Google Tensor G5",
    space: 128,
    frontCamera: "12 MP",
    rearCamera: "50 MP + 48 MP + 12 MP",
    mainCamera: "50 MP (OIS)",
    battery: "5000 mAh",
    rating: 4.5,
    purchases: 1200,
    review: "Insane camera quality! Low-light photos are unbelievable. Software experience is super smooth."
  },
  {
    id: 2,
    title: "Apple iPhone 17",
    image: "/Images/Mobiles/i phone 17.webp",
    price: 99999,
    processor: "A19 Bionic",
    space: 128,
    frontCamera: "12 MP",
    rearCamera: "48 MP + 12 MP",
    mainCamera: "48 MP (OIS)",
    battery: "4200 mAh",
    rating: 4.7,
    purchases: 1800,
    review: "Super performance and best battery optimization. Perfect choice for Apple users."
  },
  {
    id: 3,
    title: "Apple iPhone 16 Pro",
    image: "/Images/Mobiles/iphone 16 pro.webp",
    price: 119999,
    processor: "A18 Pro",
    space: 128,
    frontCamera: "12 MP",
    rearCamera: "48 MP + 12 MP + 12 MP",
    mainCamera: "48 MP (OIS)",
    battery: "4500 mAh",
    rating: 4.8,
    purchases: 2400,
    review: "The display and video stabilization are on another level. Premium build."
  },
  {
    id: 4,
    title: "Apple iPhone 16",
    image: "/Images/Mobiles/iphone 16.webp",
    price: 84999,
    processor: "A18 Bionic",
    space: 128,
    frontCamera: "12 MP",
    rearCamera: "48 MP + 12 MP",
    mainCamera: "48 MP (OIS)",
    battery: "4200 mAh",
    rating: 4.6,
    purchases: 1600,
    review: "Perfect size to hold, buttery-smooth performance, good value in Apple ecosystem."
  },
  {
    id: 5,
    title: "Moto Edge 60",
    image: "/Images/Mobiles/moto edge 60.webp",
    price: 52999,
    processor: "Snapdragon 8s Gen 3",
    space: 128,
    frontCamera: "32 MP",
    rearCamera: "50 MP + 16 MP + 8 MP",
    mainCamera: "50 MP (OIS)",
    battery: "5100 mAh",
    rating: 4.3,
    purchases: 900,
    review: "Clean UI and blazing-fast charging. Great value for performance lovers."
  },
  {
    id: 6,
    title: "Nothing Phone 3a",
    image: "/Images/Mobiles/Nothing 3a.webp",
    price: 38999,
    processor: "Snapdragon 8 Gen 2",
    space: 128,
    frontCamera: "32 MP",
    rearCamera: "50 MP + 50 MP",
    mainCamera: "50 MP (OIS)",
    battery: "5000 mAh",
    rating: 4.4,
    purchases: 1500,
    review: "Unique transparent design with solid camera performance. Totally worth the price."
  },
  {
    id: 7,
    title: "Samsung Galaxy S24",
    image: "/Images/Mobiles/S24.webp",
    price: 79999,
    processor: "Snapdragon 8 Gen 3",
    space: 128,
    frontCamera: "32 MP",
    rearCamera: "50 MP + 10 MP + 12 MP",
    mainCamera: "50 MP (OIS)",
    battery: "4000 mAh",
    rating: 4.6,
    purchases: 2100,
    review: "Compact, powerful, and the display is stunning. Best one-handed Android flagship."
  },
  {
    id: 8,
    title: "Samsung Galaxy S25 Ultra",
    image: "/Images/Mobiles/S25 ultra.webp",
    price: 139999,
    processor: "Snapdragon 8 Gen 4",
    space: 128,
    frontCamera: "40 MP",
    rearCamera: "200 MP + 50 MP + 50 MP + 12 MP",
    mainCamera: "200 MP (OIS)",
    battery: "5500 mAh",
    rating: 4.9,
    purchases: 3100,
    review: "Monster performance and insane 200MP zoom camera. The king of Android phones."
  },
  {
    id: 9,
    title: "Vivo T4 Ultra",
    image: "/Images/Mobiles/Vivo T4 ultra.webp",
    price: 45999,
    processor: "Dimensity 9400",
    space: 128,
    frontCamera: "50 MP",
    rearCamera: "64 MP + 16 MP + 8 MP",
    mainCamera: "64 MP (OIS)",
    battery: "5200 mAh",
    rating: 4.2,
    purchases: 800,
    review: "Amazing camera colors and performance. Good battery backup for heavy users."
  }
];
